### ISSUE TITLE
Port to firefox

### ISSUE THREAD

**Issue by mine260309** [androidyue/Gmail-Helper-Filter#1]
As a heavy Firefox user, I would like to port this extension to Firefox.

Ref:
https://hacks.mozilla.org/2015/10/porting-chrome-extensions-to-firefox-with-webextensions/
http://stackoverflow.com/questions/17967442/convert-google-chrome-extension-to-firefox-or-safari-extension

I can help on this if you think it's OK.

**Comment by androidyue** [comment]
Yes, I think it's OK.

in the Addon please add a link to the github repo so that others can access the source and contribute if they want. 

Port the extension to firefox and let me know when it's released. And I  I want to  add the firefox-addon url address into README.md.

Thank you and Cheers.

**Comment by mine260309** [comment]
Firefox support is done at Pull Request #2

**Comment by androidyue** [comment]
@mine260309  How can I get the firefox extension? Is there any link?

**Comment by mine260309** [comment]
Just create a zip package, e.g. `zip test.xpi *`, and install the XPI in Firefox.

**Comment by androidyue** [comment]
@mine260309  I installed, But it could not be able to create filter.   Does it work on your side?

**Comment by mine260309** [comment]
Yes, it works on Firefox 44.0 on Ubuntu 14.04.
You can check the console log by pressing Ctrl-Shift-J and see what's wrong.

**Comment by androidyue** [comment]
@mine260309  I moved a small further step. It works at the first time and then It only displays a blank page without items.  I will try to resolve  the problem when I am free.
